#!/usr/bin/python
#coding=utf-8
'''
Created on 2015-11-29
@author: ymy
Copyright ymyjohnny@gmail.com
'''


#找出chardet.html中的a标签

from bs4 import BeautifulSoup

f = open("chardet.html")

soup = BeautifulSoup(f.read())


